### ISSUE TITLE
Restitution de la situation Sécurité

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro-serveur#184]
Afficher de manière brute dans la restitution Sécurité les métriques suivantes:

- [x] Mémoire de travail/ Vitesse d'éxécution #180
- [x] Compréhension du langage #192 
- [x] Métacognition (certitude dans ses pensées) #182 
- [x] Orientation visuo-spatiale #187 
- [x] Résolution de problèmes #180
- [x] Planification : 
    - [x] Mesure de la rapidité d’identification du premier danger à partir du début de la tâche #188
    - [x] Mesure de la rapidité d’identification après chaque fin de qualification d’incident (la fenêtre se ferme, le compteur se lance) #190 
    - [x] Calcul du temps moyen pour la personne et comparaison au temps moyen de la cohorte (ou groupe de référence) #195 
- [x] Inhibition #193 
- [x] Attention visuo-spatiale
- [x] Attention sélective #185 

Source (cliquer sur scoring): [https://docs.google.com/document/d/1Eu4sFjkNye1Mlw-JajbPXhU_m1Snyt30P37bSd1uF5Q/edit#](https://docs.google.com/document/d/1Eu4sFjkNye1Mlw-JajbPXhU_m1Snyt30P37bSd1uF5Q/edit#)
