### ISSUE TITLE
Restitution prescripteur avec les compétences triées

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#201]
- [x] Renomme les compétences fortes en compétences de la meilleure restitution #202 
- [x] Affiche dans l'admin les compétences triées #203 
- [x] Ignorer les compétences Persévérence et Compréhension de consigne #204 
- [ ] Retourner dans l'API les compétences triées
