### ISSUE TITLE
Évalue la situation inventaire

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#45]
- [x] Persévérance #52 
- [x] Compréhension de la consigne #53
- [x] Niveau de vigilance et de contrôle #55 
- [x] Rapidité de traitement #49
- [x] Organisation et méthode #47 
- [x] Efficience globale #54
