### ISSUE TITLE
Évaluation de la situation tri

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#63]
- [x] Informations basiques nombre erreurs et temps #66 
- [x] Compétence Comparaison et tri #70
- [x] Compétence Rapidité de Traitement  #69 
- [x] Compétence persévérance #71 
- [x] Compétence compréhension de la consigne #72 
- [x] Affichage dans la restitution globale #68
