### ISSUE TITLE
Introduction d'une campagne pour relier les évaluations et configurer

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#88]
- [x] Créer la campagne dans l'admin #95 
- [x] Relier une évaluation à une campagne (avec ou sans code) #96 
- [x] Afficher les évaluations d'une campagne dans sa fiche #99 
- [x] Générer automatiquement le code de la campagne #105 
- [x] Forcer le passage du code de campagne ?
- [x] Spécifier quelle situation doit être jouée et dans quelle ordre
- [x] Ajoute l'illustration coté question
